CREATE DATABASE University;
GO

USE University;

CREATE TABLE COURSES
(
  Id INT NOT NULL PRIMARY KEY,
  [Name] NVARCHAR(20) NOT NULL,
  [Description] NVARCHAR(20) NOT NULL
)

CREATE TABLE GROUPS
(
    Id INT NOT NULL PRIMARY KEY,
    Course_id INT  NOT NULL REFERENCES COURSES(Id) ON DELETE CASCADE,
    [Name] NVARCHAR(20) NOT NULL
);

CREATE TABLE STUDENTS
(
  Id INT NOT NULL PRIMARY KEY,
  Group_id INT NOT NULL REFERENCES GROUPS(Id) ON DELETE CASCADE,
  FirstName NVARCHAR(20) NOT NULL,
  LastName NVARCHAR(20) NOT NULL
);